version: "3.9"
services:
  postgres:
    image: "postgres:13.1-alpine"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    volumes: 
      - ".postgres:/var/lib/postgresql/data"
  redis: 
    image: "redis:alpine"
  api:
    build: .
    ports: 
      - "3000:3000" 
    depends_on: 
      - postgres
      - redis
    environment: 
      - DATABASE_HOST=postgres 
      - DATABASE_PORT=5432
      - DATABASE_NAME=to_do_notion_api_development
      - DATABASE_USERNAME=postgres
      - RAILS_ENV=development
      - HTTPS=false
      - RACK_ENV=development
    volumes: 
      - .:/usr/src/app
# volumes: 
#   postgres_data: 